name: Deploy DAGs
run-name: Deploy ${{ inputs.tag }} to ${{ inputs.deploy_target }}-${{ inputs.domain }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        required: true
        description: 'The target environment to deploy to'
        type: choice
        options: ['development', 'production']
      domain:
        required: true
        description: 'The domain to deploy to'
        type: choice
        options: ['uk', 'india']
      tag:
        required: true
        description: The repo tag to deploy
        type: string
  workflow_call:
    inputs:
      deploy_target:
        required: false
        default: 'development'
        description: 'The target environment to deploy to'
        type: string
      domain:
        required: true
        description: 'The domain to deploy to'
        type: string
      tag:
        required: true
        description: The repo tag to deploy
        type: string

jobs:
  deploy-dags:
    runs-on: ubuntu-latest
    environment: "${{ inputs.deploy_target }}-${{ inputs.domain }}"
    env:
      BUCKET_NAME: "${{ inputs.domain }}-${{ inputs.deploy_target }}-eb-airflow"
      DOMAIN: "${{ inputs.domain }}"
      REGION: "${{ inputs.domain == 'india' && 'ap-south-1' || 'eu-west-1' }}"

    steps:
      - name: Checkout required tag
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[vars.KEY__AWS_ACCESS_KEY_ID] }}
          aws-secret-access-key: ${{ secrets[vars.KEY__AWS_SECRET_ACCESS_KEY] }}
          aws-region: ${{ env.REGION }}

      - name: Create domain .airflowignore file
        run: |
          echo "*/" >> src/airflow_dags/dags/.airflowignore
          echo !${DOMAIN}/ >> src/airflow_dags/dags/.airflowignore
          cat src/airflow_dags/dags/.airflowignore

      - name: Deploy to S3 dagbag
        run: aws s3 sync src/airflow_dags s3://$BUCKET_NAME/dags/airflow_dags --delete

