name: SemVer Tag Created CI
run-name: Deploy ${{ github.ref }} to development by ${{ github.actor }}

on:
  push:
    tags: ["v*.*.*"]

jobs:
  deploy-dags-dev:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domain: [ "uk", "india" ]
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_target: "development"
      domain: ${{ matrix.domain }}
      tag: ${{ github.ref }}

